import 'package:jog_inventory/common/utils/date_formater.dart';
import 'package:jog_inventory/common/utils/validation.dart';
import 'package:jog_inventory/modules/material/models/fabric.dart';
import 'package:jog_inventory/modules/no_code/controllers/no_code_request.dart';
import 'package:jog_inventory/modules/no_code/widgits/fabric_detail.dart';
import '../../../common/exports/main_export.dart';

class NoCodeRequestFormScreen extends GetView<NoCodeRequestController> {
  const NoCodeRequestFormScreen({super.key});

  NoCodeRequestController get controller =>
      getController<NoCodeRequestController>(NoCodeRequestController());

  @override
  Widget build(BuildContext context) {
    return CustomAppBar(
        title: Strings.noCodeRQ, body: body(), bottomNavBar: viewWidget());
  }

  Widget body() {
    return SingleChildScrollView(
      padding: AppPadding.pagePadding,
      child: Form(
        key: controller.formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(Strings.requisitionWithNoCode,
                style: appTextTheme.titleMedium),

            /// form
            gap(),
            Row(
              children: [
                // code
                Expanded(child: autoGenerateCodeWidget()),
                gap(),
                //date
                Expanded(child: dateWidget()),
              ],
            ),

            gap(),
            // note
            noteWidget(),

            ///
            gap(),
            safeAreaBottom(Get.context!),
          ],
        ),
      ),
    );
  }

  Widget autoGenerateCodeWidget() {
    return TextFieldWithLabel(
        labelText: Strings.autoGenCode,
        enabled: false,
        hintText: controller.autoGeneratedCodeStr);
  }

  Widget dateWidget() {
    return TextFieldWithLabel(
        labelText: Strings.date,
        enabled: false,
        hintText: appDateTimeFormat.toYYMMDDHHMMSS());
  }

  Widget noteWidget() {
    return TextFieldWithLabel(
        labelText: Strings.note,
        enabled: true,
        hintText: Strings.enterComments,
        validator: appValidation.validateEmptyField,
        controller: controller.noteController,
        maxLines: 2);
  }

  Widget submitButton() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Container(
          height: 50,
          child: ClipRRect(
              child: PrimaryButton(
            title: Strings.submit,
            onTap: () {},
            isFullWidth: false,
            radius: 15,
          )),
        ),
      ],
    );
  }

  Widget viewWidget() {
    return Obx(
      () => Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          gap(),
          Visibility(
            visible: !controller.isCodeGenerated.value,
            child: PrimaryButton(
                isBusy: controller.isBusy.value,
                title: "Submit",
                onTap: () {
                  controller.createNoCodeRequest();
                }),
          ),
          if (controller.isCodeGenerated.value) ...[
            Row(
              children: [
                // Expanded(
                //   child: CustomDropDownWithLabel(
                //     items: [],
                //     onChanged: (item) {},
                //     labelText: Strings.selectType,
                //     hintText: Strings.selectType,
                //   ),
                // ),
                // gap(),
                Expanded(
                  child: bottomSheetMenuWithLabel<FabricTypeModel>(
                    controller: controller.selectMaterialController,
                    items: [],
                    fromApi: () async {
                      var data = await FabricTypeModel.fetchAll();
                      return List.generate(
                          data.length,
                          (index) => DropDownItem<FabricTypeModel>(
                              id: index,
                              title: '${data[index].catNameEn}',
                              key: '${index}',
                              value: data[index]));
                    },
                    onChanged: (item) {
                      controller.categoryId = item?.firstOrNull?.value?.catId?.toString();
                    },
                    labelText: Strings.selectMaterial,
                    hintText: Strings.selectMaterial,
                  ),
                ),
              ],
            ),
            gap(space: 10),
            dottedDivider(),
            gap(space: 10),
            Row(
              children: [
                Expanded(
                  child: ClipRRect(
                      child: PrimaryButton(
                    title: Strings.view,
                    color: Colours.greenLight,
                    leading: Icon(
                      Icons.remove_red_eye,
                      color: Colours.white,
                      size: 20,
                    ),
                    onTap: () {
                      if (controller.categoryId == null)
                        errorSnackBar(message: "Select material type");
                      else
                        openFabricDetailsPopup(controller.categoryId!,
                            onDone: () {
                          controller.selectMaterialController.resetItems;
                        });
                    },
                    isFullWidth: false,
                    radius: 15,
                  )),
                ),
              ],
            )
          ],
        ],
      ),
    );
  }
}
