import 'package:jog_inventory/common/utils/date_formater.dart';
import 'package:jog_inventory/modules/no_code/models/no_code.dart';
import '../../../common/exports/main_export.dart';

class NoCodeRequestController extends GetxController {
  RxBool isLoading = false.obs;
  RxBool isBusy = false.obs;
  RxBool isCodeGenerated = false.obs;
  String? usedCode;

  final GlobalKey<FormState> formKey = GlobalKey<FormState>();

  String autoGeneratedCodeStr = generateCodeFromDateTime();
  String currentDate = appDateTimeFormat.toYYMMDDHHMMSS();
  TextEditingController noteController = TextEditingController();

  BottomSheetItemMenuController selectMaterialController =
      BottomSheetItemMenuController();
  String? categoryId;

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  /// functions
  createNoCodeRequest() {
    if (formKey.currentState?.validate() ?? false) {
      isBusy.value = true;
      var data = NoCodeRequestModel(
          no_order_note: noteController.text,
          used_code: autoGeneratedCodeStr,
          used_date: currentDate);
      data.create().then((onValue) {
        usedCode = "${onValue.data['data']}";
        isCodeGenerated.value = true;
        isBusy.value = false;
      }).onError((error, trace) {
        isBusy.value = false;
        errorSnackBar(message: "Error posting data");
      });
    }
  }

  /// get and register controller
  static NoCodeRequestController getController<T>() {
    var isRegistered = Get.isRegistered<NoCodeRequestController>();
    if (isRegistered) {
      return Get.find<NoCodeRequestController>();
    }
    return Get.put<NoCodeRequestController>(NoCodeRequestController());
  }

  /// api calls
}
