// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0uCXPvAajea7osUeBkwV_aqP18axDkY',
    appId: '1:566109691338:web:ec1c07ce29228725a00333',
    messagingSenderId: '566109691338',
    projectId: 'jog-inventory',
    authDomain: 'jog-inventory.firebaseapp.com',
    storageBucket: 'jog-inventory.appspot.com',
    measurementId: 'G-SM2Q5K2MWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVscZEmotoehVdCnJUVv50grq7PB2j6AQ',
    appId: '1:566109691338:android:cfb2a6912277165ca00333',
    messagingSenderId: '566109691338',
    projectId: 'jog-inventory',
    storageBucket: 'jog-inventory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OtJIRQWAXnWGNL5oZsMAfMLNimMzhFg',
    appId: '1:566109691338:ios:e5ebce86c0ac15eea00333',
    messagingSenderId: '566109691338',
    projectId: 'jog-inventory',
    storageBucket: 'jog-inventory.appspot.com',
    iosBundleId: 'com.jogdigitialinnovations.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OtJIRQWAXnWGNL5oZsMAfMLNimMzhFg',
    appId: '1:566109691338:ios:7d862d0ff2debf91a00333',
    messagingSenderId: '566109691338',
    projectId: 'jog-inventory',
    storageBucket: 'jog-inventory.appspot.com',
    iosBundleId: 'com.joginventory.jogInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj0uCXPvAajea7osUeBkwV_aqP18axDkY',
    appId: '1:566109691338:web:206e436c97c88afba00333',
    messagingSenderId: '566109691338',
    projectId: 'jog-inventory',
    authDomain: 'jog-inventory.firebaseapp.com',
    storageBucket: 'jog-inventory.appspot.com',
    measurementId: 'G-VKVCLDNDY3',
  );
}
